#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY . .
RUN dotnet restore "EndPoint/Refahi.Notif.EndPoint.Razor2/Refahi.Notif.EndPoint.Razor.csproj"

WORKDIR "/src/EndPoint/Refahi.Notif.EndPoint.Razor2"
ENV ASPNETCORE_ENVIRONMENT Development
RUN dotnet build "Refahi.Notif.EndPoint.Razor.csproj" -c Release -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Refahi.Notif.EndPoint.Razor.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Refahi.Notif.EndPoint.Razor.dll"]