//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShatelServiceReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", ConfigurationName = "ShatelServiceReference.CompositeSmsGateway")]
    public interface CompositeSmsGateway
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.getReportByMsgIdResponse> getReportByMsgIdAsync(ShatelServiceReference.getReportByMsgId request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.getReceivedMsgResponse> getReceivedMsgAsync(ShatelServiceReference.getReceivedMsg request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.sendSmsToPortResponse> sendSmsToPortAsync(ShatelServiceReference.sendSmsToPort request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.sendSmsResponse> sendSmsAsync(ShatelServiceReference.sendSms request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.getMessageIdsResponse> getMessageIdsAsync(ShatelServiceReference.getMessageIds request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.getUserCreditResponse> getUserCreditAsync(ShatelServiceReference.getUserCredit request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.getUserExactCreditResponse> getUserExactCreditAsync(ShatelServiceReference.getUserExactCredit request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseResult))]
        System.Threading.Tasks.Task<ShatelServiceReference.getChargeOnDeliveryReportResponse> getChargeOnDeliveryReportAsync(ShatelServiceReference.getChargeOnDeliveryReport request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class userCredential
    {

        private string passwordField;

        private string usernameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(chargeOnDelivery))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://accounting.webService.aaa.services.sdp.peykasa.com/")]
    public abstract partial class baseEntity
    {

        private long idField;

        private bool idFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://accounting.webService.aaa.services.sdp.peykasa.com/")]
    public partial class chargeOnDelivery : baseEntity
    {

        private long accountIdField;

        private double amountField;

        private bool amountFieldSpecified;

        private string descriptionField;

        private long msgIdField;

        private bool msgIdFieldSpecified;

        private int partCountField;

        private bool partCountFieldSpecified;

        private string resourceField;

        private int statusField;

        private bool statusFieldSpecified;

        private System.DateTime transactionDateField;

        private bool transactionDateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public long msgId
        {
            get
            {
                return this.msgIdField;
            }
            set
            {
                this.msgIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool msgIdSpecified
        {
            get
            {
                return this.msgIdFieldSpecified;
            }
            set
            {
                this.msgIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int partCount
        {
            get
            {
                return this.partCountField;
            }
            set
            {
                this.partCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partCountSpecified
        {
            get
            {
                return this.partCountFieldSpecified;
            }
            set
            {
                this.partCountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public System.DateTime transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified
        {
            get
            {
                return this.transactionDateFieldSpecified;
            }
            set
            {
                this.transactionDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class reportMessageIds
    {

        private long messageIdField;

        private bool messageIdFieldSpecified;

        private string orderIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageIdSpecified
        {
            get
            {
                return this.messageIdFieldSpecified;
            }
            set
            {
                this.messageIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string orderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class receivedMsg
    {

        private string bodyField;

        private string destinationField;

        private int encodingField;

        private long idField;

        private int partCountField;

        private long receivedTimeField;

        private string sourceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int partCount
        {
            get
            {
                return this.partCountField;
            }
            set
            {
                this.partCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public long receivedTime
        {
            get
            {
                return this.receivedTimeField;
            }
            set
            {
                this.receivedTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class reportItem
    {

        private long deliveryDateField;

        private string destinationField;

        private long msgIdField;

        private string sourceField;

        private int statusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public long deliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public long msgId
        {
            get
            {
                return this.msgIdField;
            }
            set
            {
                this.msgIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(chargeOnDeliveryResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(userExactCreditResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(userCreditResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(reportMessageIdsResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sendSmsResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getReceivedMsgResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getReportByMsgIdResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class baseResult
    {

        private string errorMsgField;

        private int statusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class chargeOnDeliveryResult : baseResult
    {

        private chargeOnDelivery[] chargeOnDeliveryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("chargeOnDelivery", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public chargeOnDelivery[] chargeOnDelivery
        {
            get
            {
                return this.chargeOnDeliveryField;
            }
            set
            {
                this.chargeOnDeliveryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class userExactCreditResult : baseResult
    {

        private double creditField;

        private bool creditFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public double credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creditSpecified
        {
            get
            {
                return this.creditFieldSpecified;
            }
            set
            {
                this.creditFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class userCreditResult : baseResult
    {

        private int creditField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class reportMessageIdsResponse : baseResult
    {

        private reportMessageIds[] reportMessageIdsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportMessageIds", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public reportMessageIds[] reportMessageIds
        {
            get
            {
                return this.reportMessageIdsField;
            }
            set
            {
                this.reportMessageIdsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class sendSmsResult : baseResult
    {

        private System.Nullable<long>[] msgIdArrayField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("msgIdArray", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public System.Nullable<long>[] msgIdArray
        {
            get
            {
                return this.msgIdArrayField;
            }
            set
            {
                this.msgIdArrayField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class getReceivedMsgResult : baseResult
    {

        private receivedMsg[] receivedMegsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("receivedMegs", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public receivedMsg[] receivedMegs
        {
            get
            {
                return this.receivedMegsField;
            }
            set
            {
                this.receivedMegsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/")]
    public partial class getReportByMsgIdResult : baseResult
    {

        private reportItem[] reportItemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reportItems", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public reportItem[] reportItems
        {
            get
            {
                return this.reportItemsField;
            }
            set
            {
                this.reportItemsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getReportByMsgId", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getReportByMsgId
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("msgIds", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] msgIds;

        public getReportByMsgId()
        {
        }

        public getReportByMsgId(ShatelServiceReference.userCredential userCredential, long[] msgIds)
        {
            this.userCredential = userCredential;
            this.msgIds = msgIds;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getReportByMsgIdResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getReportByMsgIdResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.getReportByMsgIdResult @return;

        public getReportByMsgIdResponse()
        {
        }

        public getReportByMsgIdResponse(ShatelServiceReference.getReportByMsgIdResult @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getReceivedMsg", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getReceivedMsg
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("destAddresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] destAddresses;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long fromTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int maxReturnedMsg;

        public getReceivedMsg()
        {
        }

        public getReceivedMsg(ShatelServiceReference.userCredential userCredential, string[] destAddresses, long fromTime, int maxReturnedMsg)
        {
            this.userCredential = userCredential;
            this.destAddresses = destAddresses;
            this.fromTime = fromTime;
            this.maxReturnedMsg = maxReturnedMsg;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getReceivedMsgResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getReceivedMsgResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.getReceivedMsgResult @return;

        public getReceivedMsgResponse()
        {
        }

        public getReceivedMsgResponse(ShatelServiceReference.getReceivedMsgResult @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendSmsToPort", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class sendSmsToPort
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("srcAddresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] srcAddresses;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute("destAddresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] destAddresses;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("msgBody", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] msgBody;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 4)]
        [System.Xml.Serialization.XmlElementAttribute("msgEncoding", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] msgEncoding;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("sourcePorts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] sourcePorts;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 6)]
        [System.Xml.Serialization.XmlElementAttribute("destinationPorts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] destinationPorts;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 7)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] campaignIds;

        public sendSmsToPort()
        {
        }

        public sendSmsToPort(ShatelServiceReference.userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding, int[] sourcePorts, int[] destinationPorts, string[] campaignIds)
        {
            this.userCredential = userCredential;
            this.srcAddresses = srcAddresses;
            this.destAddresses = destAddresses;
            this.msgBody = msgBody;
            this.msgEncoding = msgEncoding;
            this.sourcePorts = sourcePorts;
            this.destinationPorts = destinationPorts;
            this.campaignIds = campaignIds;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendSmsToPortResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class sendSmsToPortResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.sendSmsResult @return;

        public sendSmsToPortResponse()
        {
        }

        public sendSmsToPortResponse(ShatelServiceReference.sendSmsResult @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendSms", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class sendSms
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("srcAddresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] srcAddresses;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute("destAddresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] destAddresses;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("msgBody", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] msgBody;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 4)]
        [System.Xml.Serialization.XmlElementAttribute("msgEncoding", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] msgEncoding;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("orderIds", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] orderIds;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 6)]
        [System.Xml.Serialization.XmlElementAttribute("campaignIds", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] campaignIds;

        public sendSms()
        {
        }

        public sendSms(ShatelServiceReference.userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding, string[] orderIds, string[] campaignIds)
        {
            this.userCredential = userCredential;
            this.srcAddresses = srcAddresses;
            this.destAddresses = destAddresses;
            this.msgBody = msgBody;
            this.msgEncoding = msgEncoding;
            this.orderIds = orderIds;
            this.campaignIds = campaignIds;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "sendSmsResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class sendSmsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.sendSmsResult @return;

        public sendSmsResponse()
        {
        }

        public sendSmsResponse(ShatelServiceReference.sendSmsResult @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMessageIds", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getMessageIds
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("orderIds", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] orderIds;

        public getMessageIds()
        {
        }

        public getMessageIds(ShatelServiceReference.userCredential userCredential, string[] orderIds)
        {
            this.userCredential = userCredential;
            this.orderIds = orderIds;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getMessageIdsResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getMessageIdsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.reportMessageIdsResponse @return;

        public getMessageIdsResponse()
        {
        }

        public getMessageIdsResponse(ShatelServiceReference.reportMessageIdsResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getUserCredit", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getUserCredit
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int panelId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long providerCode;

        public getUserCredit()
        {
        }

        public getUserCredit(ShatelServiceReference.userCredential userCredential, int panelId, int customerId, long providerCode)
        {
            this.userCredential = userCredential;
            this.panelId = panelId;
            this.customerId = customerId;
            this.providerCode = providerCode;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getUserCreditResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getUserCreditResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCreditResult @return;

        public getUserCreditResponse()
        {
        }

        public getUserCreditResponse(ShatelServiceReference.userCreditResult @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getUserExactCredit", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getUserExactCredit
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int panelId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long providerCode;

        public getUserExactCredit()
        {
        }

        public getUserExactCredit(ShatelServiceReference.userCredential userCredential, int panelId, int customerId, long providerCode)
        {
            this.userCredential = userCredential;
            this.panelId = panelId;
            this.customerId = customerId;
            this.providerCode = providerCode;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getUserExactCreditResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getUserExactCreditResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userExactCreditResult @return;

        public getUserExactCreditResponse()
        {
        }

        public getUserExactCreditResponse(ShatelServiceReference.userExactCreditResult @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getChargeOnDeliveryReport", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getChargeOnDeliveryReport
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.userCredential userCredential;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resourceNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long fromTime;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long toTime;

        public getChargeOnDeliveryReport()
        {
        }

        public getChargeOnDeliveryReport(ShatelServiceReference.userCredential userCredential, string resourceNumber, long fromTime, long toTime)
        {
            this.userCredential = userCredential;
            this.resourceNumber = resourceNumber;
            this.fromTime = fromTime;
            this.toTime = toTime;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getChargeOnDeliveryReportResponse", WrapperNamespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", IsWrapped = true)]
    public partial class getChargeOnDeliveryReportResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://webService.compositeSmsGateway.services.sdp.peykasa.com/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShatelServiceReference.chargeOnDeliveryResult @return;

        public getChargeOnDeliveryReportResponse()
        {
        }

        public getChargeOnDeliveryReportResponse(ShatelServiceReference.chargeOnDeliveryResult @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CompositeSmsGatewayChannel : ShatelServiceReference.CompositeSmsGateway, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CompositeSmsGatewayClient : System.ServiceModel.ClientBase<ShatelServiceReference.CompositeSmsGateway>, ShatelServiceReference.CompositeSmsGateway
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public CompositeSmsGatewayClient() :
                base(CompositeSmsGatewayClient.GetDefaultBinding(), CompositeSmsGatewayClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CompositeSmsGatewayPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CompositeSmsGatewayClient(EndpointConfiguration endpointConfiguration) :
                base(CompositeSmsGatewayClient.GetBindingForEndpoint(endpointConfiguration), CompositeSmsGatewayClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CompositeSmsGatewayClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(CompositeSmsGatewayClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CompositeSmsGatewayClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(CompositeSmsGatewayClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CompositeSmsGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.getReportByMsgIdResponse> ShatelServiceReference.CompositeSmsGateway.getReportByMsgIdAsync(ShatelServiceReference.getReportByMsgId request)
        {
            return base.Channel.getReportByMsgIdAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.getReportByMsgIdResponse> getReportByMsgIdAsync(ShatelServiceReference.userCredential userCredential, long[] msgIds)
        {
            ShatelServiceReference.getReportByMsgId inValue = new ShatelServiceReference.getReportByMsgId();
            inValue.userCredential = userCredential;
            inValue.msgIds = msgIds;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).getReportByMsgIdAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.getReceivedMsgResponse> ShatelServiceReference.CompositeSmsGateway.getReceivedMsgAsync(ShatelServiceReference.getReceivedMsg request)
        {
            return base.Channel.getReceivedMsgAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.getReceivedMsgResponse> getReceivedMsgAsync(ShatelServiceReference.userCredential userCredential, string[] destAddresses, long fromTime, int maxReturnedMsg)
        {
            ShatelServiceReference.getReceivedMsg inValue = new ShatelServiceReference.getReceivedMsg();
            inValue.userCredential = userCredential;
            inValue.destAddresses = destAddresses;
            inValue.fromTime = fromTime;
            inValue.maxReturnedMsg = maxReturnedMsg;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).getReceivedMsgAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.sendSmsToPortResponse> ShatelServiceReference.CompositeSmsGateway.sendSmsToPortAsync(ShatelServiceReference.sendSmsToPort request)
        {
            return base.Channel.sendSmsToPortAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.sendSmsToPortResponse> sendSmsToPortAsync(ShatelServiceReference.userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding, int[] sourcePorts, int[] destinationPorts, string[] campaignIds)
        {
            ShatelServiceReference.sendSmsToPort inValue = new ShatelServiceReference.sendSmsToPort();
            inValue.userCredential = userCredential;
            inValue.srcAddresses = srcAddresses;
            inValue.destAddresses = destAddresses;
            inValue.msgBody = msgBody;
            inValue.msgEncoding = msgEncoding;
            inValue.sourcePorts = sourcePorts;
            inValue.destinationPorts = destinationPorts;
            inValue.campaignIds = campaignIds;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).sendSmsToPortAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.sendSmsResponse> ShatelServiceReference.CompositeSmsGateway.sendSmsAsync(ShatelServiceReference.sendSms request)
        {
            return base.Channel.sendSmsAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.sendSmsResponse> sendSmsAsync(ShatelServiceReference.userCredential userCredential, string[] srcAddresses, string[] destAddresses, string[] msgBody, int[] msgEncoding, string[] orderIds, string[] campaignIds)
        {
            ShatelServiceReference.sendSms inValue = new ShatelServiceReference.sendSms();
            inValue.userCredential = userCredential;
            inValue.srcAddresses = srcAddresses;
            inValue.destAddresses = destAddresses;
            inValue.msgBody = msgBody;
            inValue.msgEncoding = msgEncoding;
            inValue.orderIds = orderIds;
            inValue.campaignIds = campaignIds;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).sendSmsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.getMessageIdsResponse> ShatelServiceReference.CompositeSmsGateway.getMessageIdsAsync(ShatelServiceReference.getMessageIds request)
        {
            return base.Channel.getMessageIdsAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.getMessageIdsResponse> getMessageIdsAsync(ShatelServiceReference.userCredential userCredential, string[] orderIds)
        {
            ShatelServiceReference.getMessageIds inValue = new ShatelServiceReference.getMessageIds();
            inValue.userCredential = userCredential;
            inValue.orderIds = orderIds;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).getMessageIdsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.getUserCreditResponse> ShatelServiceReference.CompositeSmsGateway.getUserCreditAsync(ShatelServiceReference.getUserCredit request)
        {
            return base.Channel.getUserCreditAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.getUserCreditResponse> getUserCreditAsync(ShatelServiceReference.userCredential userCredential, int panelId, int customerId, long providerCode)
        {
            ShatelServiceReference.getUserCredit inValue = new ShatelServiceReference.getUserCredit();
            inValue.userCredential = userCredential;
            inValue.panelId = panelId;
            inValue.customerId = customerId;
            inValue.providerCode = providerCode;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).getUserCreditAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.getUserExactCreditResponse> ShatelServiceReference.CompositeSmsGateway.getUserExactCreditAsync(ShatelServiceReference.getUserExactCredit request)
        {
            return base.Channel.getUserExactCreditAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.getUserExactCreditResponse> getUserExactCreditAsync(ShatelServiceReference.userCredential userCredential, int panelId, int customerId, long providerCode)
        {
            ShatelServiceReference.getUserExactCredit inValue = new ShatelServiceReference.getUserExactCredit();
            inValue.userCredential = userCredential;
            inValue.panelId = panelId;
            inValue.customerId = customerId;
            inValue.providerCode = providerCode;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).getUserExactCreditAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShatelServiceReference.getChargeOnDeliveryReportResponse> ShatelServiceReference.CompositeSmsGateway.getChargeOnDeliveryReportAsync(ShatelServiceReference.getChargeOnDeliveryReport request)
        {
            return base.Channel.getChargeOnDeliveryReportAsync(request);
        }

        public System.Threading.Tasks.Task<ShatelServiceReference.getChargeOnDeliveryReportResponse> getChargeOnDeliveryReportAsync(ShatelServiceReference.userCredential userCredential, string resourceNumber, long fromTime, long toTime)
        {
            ShatelServiceReference.getChargeOnDeliveryReport inValue = new ShatelServiceReference.getChargeOnDeliveryReport();
            inValue.userCredential = userCredential;
            inValue.resourceNumber = resourceNumber;
            inValue.fromTime = fromTime;
            inValue.toTime = toTime;
            return ((ShatelServiceReference.CompositeSmsGateway)(this)).getChargeOnDeliveryReportAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompositeSmsGatewayPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompositeSmsGatewayPort))
            {
                return new System.ServiceModel.EndpointAddress("https://shmsmsws.shatelmobile.ir/services/CompositeSmsGateway");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CompositeSmsGatewayClient.GetBindingForEndpoint(EndpointConfiguration.CompositeSmsGatewayPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CompositeSmsGatewayClient.GetEndpointAddress(EndpointConfiguration.CompositeSmsGatewayPort);
        }

        public enum EndpointConfiguration
        {

            CompositeSmsGatewayPort,
        }
    }
}
