// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refahi.Notif.Infrastructure.Persistence.SqlServer.Context;

#nullable disable

namespace Refahi.Notif.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(SqlNotifContext))]
    [Migration("20241107184808_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Refahi.Notif.Domain.Contract.Models.SettingModel", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.Entities.NotificationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("EventDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("EventName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FCMMessageId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("NotificationEvents");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AppName")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Owner")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValidatorUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("App")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("NotificationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NotificationToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.Inbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppName")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AppName")
                        .IsUnique();

                    b.ToTable("Inbox");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("DeliveredTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("DateTime");

                    b.Property<string>("Icon")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("InboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("DateTime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("InboxId");

                    b.ToTable("InboxMessages");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.VerifyMessageAgg.VerifyMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeliverTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdInProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAudio")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Template")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VerifyMessages");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.Entities.Tag", b =>
                {
                    b.HasOne("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.Message", null)
                        .WithMany("Tags")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.Message", b =>
                {
                    b.OwnsOne("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Addresses")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DueTime")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("IsHtml")
                                .HasColumnType("bit");

                            b1.Property<int>("RetryCount")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("SendTime")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.OwnsOne("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.ValueObjects.Notification", "Notification", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<DateTime?>("DueTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("ExpiredDate")
                                .HasColumnType("DateTime");

                            b1.Property<string>("Icon")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<string>("Link")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.Property<string>("ValidatorUrl")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.HasKey("MessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.OwnsOne("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.ValueObjects.PushNotification", "PushNotification", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DueTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Jobs")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Url")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ValidatorUrl")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.HasKey("MessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.OwnsOne("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.ValueObjects.Sms", "Sms", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DeliverTime")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("DueTime")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Gateway")
                                .HasColumnType("int");

                            b1.Property<string>("IdInProvider")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumbers")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("RetryCount")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("SendTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Sender")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<string>("ValidatorUrl")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.HasKey("MessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.OwnsOne("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.ValueObjects.Telegram", "Telegram", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Body")
                                .HasMaxLength(1024)
                                .HasColumnType("nvarchar(1024)");

                            b1.Property<string>("ChatId")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<DateTime?>("DueTime")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FileId")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<int>("RetryCount")
                                .HasColumnType("int");

                            b1.Property<string>("SendResult")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<string>("ValidatorUrl")
                                .HasMaxLength(512)
                                .HasColumnType("nvarchar(512)");

                            b1.HasKey("MessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Notification");

                    b.Navigation("PushNotification");

                    b.Navigation("Sms");

                    b.Navigation("Telegram");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.Device", b =>
                {
                    b.HasOne("Refahi.Notif.Domain.Core.Aggregates.UserAgg.User", null)
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.Inbox", b =>
                {
                    b.HasOne("Refahi.Notif.Domain.Core.Aggregates.UserAgg.User", null)
                        .WithMany("Inboxes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.InboxMessage", b =>
                {
                    b.HasOne("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.Inbox", "Inbox")
                        .WithMany("Messages")
                        .HasForeignKey("InboxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inbox");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.MessageAgg.Message", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.Entities.Inbox", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Refahi.Notif.Domain.Core.Aggregates.UserAgg.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Inboxes");
                });
#pragma warning restore 612, 618
        }
    }
}
